# Generated by Django 3.1.5 on 2021-04-13 11:01

from django.conf import settings
import django.contrib.auth.backends
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('pnome', models.CharField(max_length=200)),
                ('unome', models.CharField(max_length=200)),
            ],
            bases=(models.Model, django.contrib.auth.backends.BaseBackend),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
                ('carteira', models.FloatField()),
                ('pnome', models.CharField(max_length=200)),
                ('unome', models.CharField(max_length=200)),
                ('fadmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(max_length=800)),
                ('imagem', models.ImageField(upload_to='')),
                ('preco', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CASA', 'Casa/Lar'), ('ELET', 'Eletrônicos'), ('AFRO', 'Produtos Afrodisiacos'), ('INFA', 'Produtos Infantis'), ('ROUP', 'Roupas')], default=None, max_length=4)),
                ('f_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data da compra')),
                ('quantidade', models.IntegerField()),
                ('lucro', models.FloatField()),
                ('fcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.cliente')),
                ('fproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.cliente')),
                ('fproduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.produto')),
            ],
        ),
    ]
