# Generated by Django 3.1.5 on 2021-02-16 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('repercussao_twitter', models.IntegerField()),
                ('avaliacao', models.FloatField(max_length=5.0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_web_app.computerpart_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('computerpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.computerpart')),
                ('nucleos', models.IntegerField()),
                ('clock', models.FloatField()),
                ('tdp', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('web_app.computerpart',),
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('computerpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.computerpart')),
                ('vram', models.IntegerField()),
                ('shaders', models.IntegerField()),
                ('tdp', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('web_app.computerpart',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('computerpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.computerpart')),
                ('soquete', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('web_app.computerpart',),
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('computerpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.computerpart')),
                ('potencia', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('web_app.computerpart',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('computerpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.computerpart')),
                ('freq', models.IntegerField()),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('web_app.computerpart',),
        ),
        migrations.CreateModel(
            name='SecondaryMemory',
            fields=[
                ('computerpart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='web_app.computerpart')),
                ('tipo', models.CharField(choices=[('SSD', 'ssd'), ('HDD', 'hdd')], default=None, max_length=3)),
                ('capacidade', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('web_app.computerpart',),
        ),
        migrations.CreateModel(
            name='NoticiaField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('data_publicacao', models.DateField()),
                ('computer_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.computerpart')),
            ],
        ),
        migrations.CreateModel(
            name='ComentariosField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('computer_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.computerpart')),
            ],
        ),
    ]
